[colors.primary]
background = '#1b1a20'
foreground = '#c9ccd5'

[colors.normal]
black = '#0f0e14'
red = '#d8878d'
green = '#97b28b'
yellow = '#dcc39b'
blue = '#8eaacd'
magenta = '#b39fcb'
cyan = '#90bfb8'
white = '#c6c8cf'

[colors.bright]
black = '#8f919c'
red = '#e7a0a4'
green = '#aac89d'
yellow = '#ecd4ab'
blue = '#a7c3ec'
magenta = '#cbb4e6'
cyan = '#a7d7cf'
white = '#d9dce6'

[colors.selection]
background = '#41546d'
foreground = '#d9dce6'

[[colors.indexed_colors]]
index = 16
color = '#d2a27f'

[[colors.indexed_colors]]
index = 17
color = '#d59495'
